apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

  destination:
    namespace: velero
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 9.0.1
    helm:
      # Values file as block file. This takes precedence over values
      valuesObject:
        ingress:
          enabled: true
          hosts:
            - host: piwigo.chpap.net
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/issuer: letsencrypt-staging53 
            #            kubernetes.io/tls-acme: "true"
          labels: {}
          tls:
            - secretName: piwigo-tls
              hosts:
                - piwigo.chpap.net

      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      #      parameters:
      # - name: "ingress.enabled"
      #  value: "true"
      #  forceString: true # ensures that value is treated as a string
      #podAnnotations:
      #    iam.amazonaws.com/role: "arn:aws:iam::250423955575:role/k3s-RoleVelero-staging"
        initContainers:
         - name: velero-plugin-for-aws
           image: velero/velero-plugin-for-aws:v1.10.0
           imagePullPolicy: IfNotPresent
           volumeMounts:
            - mountPath: /target
              name: plugins


        configuration:
  # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
  # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
          backupStorageLocation:
    # name is the name of the backup storage location where backups should be stored. If a name is not provided,
    # a backup storage location will be created with the name "default". Optional.
    # provider is the name for the backup storage location provider.
          - provider: "aws"
    # bucket is the name of the bucket to store backups in. Required.
            bucket: "velerok3s-cluster-a7d88b34abfe90dac7c49fe32246175c"
    # caCert defines a base64 encoded CA bundle to use when verifying TLS connections to the provider. Optional.
    # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
            prefix: "velero"
    # default indicates this location is the default backup storage location. Optional.
            default: true
    # validationFrequency defines how frequently Velero should validate the object storage. Optional.
    # accessMode determines if velero can write to this backup storage location. Optional.
    # default to ReadWrite, ReadOnly is used during migrations and restores.
            accessMode: ReadWrite
            config: 
              region: "eu-north-1"
    #          serviceAccount: "velero-sa"
    #  s3ForcePathStyle:
    #  s3Url:
    #  kmsKeyId:
    #  resourceGroup:
    #  The ID of the subscription containing the storage account, if different from the cluster’s subscription. (Azure only)
    #  subscriptionId:
    #  storageAccount:
    #  publicUrl:
    #  ame of the GCP service account to use for this backup storage location. Specify the
    #  service account here if you want to use workload identity instead of providing the key file.(GCP only)
    #  et up for Velero.
    #
          volumeSnapshotLocation:
    # name is the name of the volume snapshot location where snapshots are being taken. Required.
    #- name:
    # provider is the name for the volume snapshot provider.
          - provider: "aws"
    # Additional provider-specific configuration. See link above
    # for details of required/optional fields for your provider.
            config:   
              region: "eu-north-1"

        credentials:
  # Whether a secret should be used. Set to false if, for examples:
  # - using kube2iam or kiam to provide AWS IAM credentials instead of providing the key file. (AWS only)
  # - using workload identity instead of providing the key file. (Azure/GCP only)
          useSecret: false
        serviceAccount:
          server:
            create: true
            name: "velero-server"
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::250423955575:role/k3s-RoleVelero-staging"
              eks.amazonaws.com/audience: "sts.amazonaws.com"
    # optional: When set to "true", adds AWS_STS_REGIONAL_ENDPOINTS env var
    #   to containers
              eks.amazonaws.com/sts-regional-endpoints: "true"
    # optional: Defaults to 86400 for expirationSeconds if not set
    #   Note: This value can be overwritten if specified in the pod
    #         annotation as shown in the next step.
              eks.amazonaws.com/token-expiration: "86400"
