apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

  destination:
    namespace: velero
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 1.0.0
    helm:
      # Values file as block file. This takes precedence over values
      valuesObject:
        ingress:
          enabled: true
          hosts:
            - host: piwigo.chpap.net
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/issuer: letsencrypt-staging53 
            #            kubernetes.io/tls-acme: "true"
          labels: {}
          tls:
            - secretName: piwigo-tls
              hosts:
                - piwigo.chpap.net

      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      #      parameters:
      # - name: "ingress.enabled"
      #  value: "true"
      #  forceString: true # ensures that value is treated as a string

        configuration:
  # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
  # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
          backupStorageLocation:
    # name is the name of the backup storage location where backups should be stored. If a name is not provided,
    # a backup storage location will be created with the name "default". Optional.
          - name: "velero_s3"
    # provider is the name for the backup storage location provider.
            provider:
    # bucket is the name of the bucket to store backups in. Required.
            bucket:
    # caCert defines a base64 encoded CA bundle to use when verifying TLS connections to the provider. Optional.
    # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
            prefix: "velero"
    # default indicates this location is the default backup storage location. Optional.
            default: true
    # validationFrequency defines how frequently Velero should validate the object storage. Optional.
    # accessMode determines if velero can write to this backup storage location. Optional.
    # default to ReadWrite, ReadOnly is used during migrations and restores.
            accessMode: ReadWrite
            config: 
    #  region:
    #  s3ForcePathStyle:
    #  s3Url:
              serviceAccount: "velero-sa"
    #  kmsKeyId:
    #  resourceGroup:
    #  The ID of the subscription containing the storage account, if different from the cluster’s subscription. (Azure only)
    #  subscriptionId:
    #  storageAccount:
    #  publicUrl:
    #  Name of the GCP service account to use for this backup storage location. Specify the
    #  service account here if you want to use workload identity instead of providing the key file.(GCP only)
