apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piwigo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

  destination:
    namespace: piwigo
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: piwigo
    repoURL: https://nicholaswilde.github.io/helm-charts/
    targetRevision: 1.0.0
    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "ingress.enabled"
        value: "true"
        forceString: true # ensures that value is treated as a string

