apiVersion: v1
kind: Namespace
metadata:
  name: helm-guestbook
---
apiVersion: v1
kind: Namespace
metadata:
  name: helm-hooks
---
apiVersion: v1
kind: Namespace
metadata:
  name: kustomize-guestbook
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: sync-waves
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
