apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

  destination:
    namespace: postgres
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: pgadmin4
    repoURL: https://helm.runix.net/
    targetRevision: 1.42.0
    helm:
      valuesObject:
        env: 
          email: tsoupap@gmail.com
        persistentVolume:
          enabled: false
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations: 
             cert-manager.io/cluster-issuer: letsencrypt-staging53
    # kubernetes.io/tls-acme: "true"
          hosts:
            - host: pgadmin4.chpap.net
              paths:
               - path: /
                 pathType: Prefix
          tls: 
            - secretName: chart-pgadmin4-tls
              hosts:
               - pgadmin4.chpap.net

# Additional config maps to be mounted inside a container
# Can be use
      # Values file as block file. This takes precedence over values
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      #      parameters:
      # - name: "ingress.enabled"
      #  value: "true"
      #  forceString: true # ensures that value is treated as a string

