apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

  destination:
    namespace: postgres
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    #chart: postgresql
    path: bitnami/postgresql
    repoURL: https://github.com/bitnami/charts.git
    #https://charts.bitnami.com/bitnami
    targetRevision: postgresql/16.6.6
    helm:
      # Values file as block file. This takes precedence over values
      valuesObject:
        tls:
  ## @param tls.enabled Enable TLS traffic support
          enabled: false
            #pgHbaConfiguration: |-
            #local all all trust
            #host all all 0.0.0.0/0 trust
            #      host    postgres        all             192.168.12.10/32        scram-sha-256
        primary:
          service:
    ## @param primary.service.type Kubernetes Service type
    ##
            type: ClusterIP
    ## @param primary.service.ports.postgresql PostgreSQL service port
