apiVersion: v1
kind: Secret
metadata:
  name: pgadmin4-oauth2-secret
type: Opaque
stringData:
  OAUTH2_CLIENT_ID: Ov23liywKLd4gKrSY8sM
  OAUTH2_CLIENT_SECRET: 1b709af97516684c6f2cb2a9472eae6e52e0c438

