apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin4-config
  namespace: postgres
data:
  config_local.py: |-
    import os
    import logging
    
    MASTER_PASSWORD_REQUIRED = True
    AUTHENTICATION_SOURCES = ['oauth2', 'internal']
    # Number of values to trust for X-Forwarded-For
    PROXY_X_FOR_COUNT = 4
    # Number of values to trust for X-Forwarded-Proto.
    PROXY_X_PROTO_COUNT = 4
    # Number of values to trust for X-Forwarded-Host.
    PROXY_X_HOST_COUNT = 4
    # Number of values to trust for X-Forwarded-Port.
    #PROXY_X_PORT_COUNT = 4
    # Number of values to trust for X-Forwarded-Prefix.
    #PROXY_X_PREFIX_COUNT = 4
    ENHANCED_COOKIE_PROTECTION=False
    WTF_CSRF_CHECK_DEFAULT=False
    WTF_CSRF_ENABLED=False
    #WTF_CSRF_HEADERS = ['X-pgA-CSRFToken', 'X-CSRFToken', 'X-CSRF-Token']
    DEBUG = True
    CONSOLE_LOG_LEVEL = logging.DEBUG
    OAUTH2_AUTO_CREATE_USER = True
    OAUTH2_CONFIG = [
      {
          'OAUTH2_NAME': 'google',
          'OAUTH2_DISPLAY_NAME': 'Google',
          'OAUTH2_CLIENT_ID': os.environ['OAUTH2_CLIENT_ID'],
          'OAUTH2_CLIENT_SECRET': os.environ['OAUTH2_CLIENT_SECRET'],
          'OAUTH2_TOKEN_URL': 'https://www.googleapis.com/oauth2/v3/token',
          'OAUTH2_AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/v2/auth',
          'OAUTH2_API_BASE_URL': 'https://www.googleapis.com/oauth2/v3/',
          'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
          'OAUTH2_ICON': 'fa-google',
          'OAUTH2_BUTTON_COLOR': '#0000ff',
      },
      {
          'OAUTH2_NAME': 'github',
          'OAUTH2_DISPLAY_NAME': 'Github',
          'OAUTH2_CLIENT_ID': os.environ['OAUTH2_CLIENT_ID'],
          'OAUTH2_CLIENT_SECRET': os.environ['OAUTH2_CLIENT_SECRET'],
          'OAUTH2_TOKEN_URL': 'https://github.com/login/oauth/access_token',
          'OAUTH2_AUTHORIZATION_URL': 'https://github.com/login/oauth/authorize',
          'OAUTH2_API_BASE_URL': 'https://api.github.com/',
          'OAUTH2_USERINFO_ENDPOINT': 'user',
          'OAUTH2_ICON': 'fa-github',
          'OAUTH2_BUTTON_COLOR': '#0000ff',
      },
      {
        'OAUTH2_NAME': 'microsoft',
        'OAUTH2_DISPLAY_NAME': 'Microsoft',
        'OAUTH2_CLIENT_ID': os.environ['OAUTH2_CLIENT_ID'],
        'OAUTH2_CLIENT_SECRET': os.environ['OAUTH2_CLIENT_SECRET'],
        'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/{YOUR_TENANT_ID}/oauth2/v2.0/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/{YOUR_TENANT_ID}/oauth2/v2.0/authorize',
        'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
        'OAUTH2_USERINFO_ENDPOINT': 'me',
        'OAUTH2_SCOPE': 'User.Read',
        'OAUTH2_ICON': 'fa-microsoft',
        'OAUTH2_BUTTON_COLOR': '#0000ff',
      },
      {
        'OAUTH2_NAME': 'microsoft-oidc',
        'OAUTH2_DISPLAY_NAME': 'Microsoft OIDC',
        'OAUTH2_CLIENT_ID': os.environ['OAUTH2_CLIENT_ID'],
        'OAUTH2_CLIENT_SECRET': os.environ['OAUTH2_CLIENT_SECRET'],
        'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/{YOUR_TENANT_ID}/oauth2/v2.0/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/{YOUR_TENANT_ID}/oauth2/v2.0/authorize',
        'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/{YOUR_TENANT_ID}/v2.0/.well-known/openid-configuration',
        'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
        'OAUTH2_USERINFO_ENDPOINT': 'https://graph.microsoft.com/oidc/userinfo',
        'OAUTH2_SCOPE': 'openid profile email',
        'OAUTH2_ICON': 'fa-microsoft',
        'OAUTH2_BUTTON_COLOR': '#0000ff',
        'OAUTH2_ADDITIONAL_CLAIMS': {
          'groups': ["{LIST_OF_YOUR_GROUP_GUIDS}"],
        }
      }
    ]
